package com.scheduler.job.queue;

import com.scheduler.job.entity.JobEntity;

import java.util.Objects;
import java.util.UUID;

/**
 * Transport contract for a job message on SQS.
 *
 * <p>Deliberately decoupled from {@link JobEntity}: the JPA entity is never serialized onto the queue,
 * so schema/persistence changes cannot silently change the wire format, and no persistence-only
 * columns (claimedBy, idempotencyKey, timestamps, lastError) leak to consumers.
 *
 * <p>The message carries exactly the five fields defined by the message contract:
 * {@code jobId}, {@code jobType}, {@code payload}, {@code retryCount}, {@code traceId}.
 *
 * <p>The message is a <em>reference plus execution context</em>, not a source of truth: the worker
 * re-reads the job from PostgreSQL and the {@code CLAIMED -> RUNNING} transition is what authorizes
 * execution. This is what makes at-least-once SQS delivery safe.
 *
 * <p>The canonical constructor validates the contract, so validation runs both on publish and on
 * Jackson deserialization of an inbound message.
 *
 * @param jobId      identifier of the job row in PostgreSQL
 * @param jobType    handler selector
 * @param payload    job payload as a JSON document
 * @param retryCount attempt counter at publication time
 * @param traceId    correlation identifier carried across scheduler, queue and worker log lines
 */
public record JobMessage(
        UUID jobId,
        String jobType,
        String payload,
        int retryCount,
        String traceId
) {

    public JobMessage {
        Objects.requireNonNull(jobId, "jobId must not be null");
        if (jobType == null || jobType.isBlank()) {
            throw new IllegalArgumentException("jobType must not be blank");
        }
        if (payload == null || payload.isBlank()) {
            throw new IllegalArgumentException("payload must not be blank");
        }
        if (retryCount < 0) {
            throw new IllegalArgumentException("retryCount must not be negative, was " + retryCount);
        }
        if (traceId == null || traceId.isBlank()) {
            throw new IllegalArgumentException("traceId must not be blank");
        }
    }

    /**
     * Builds a queue message from a persisted job.
     *
     * @param job     the job being published; must carry a persisted id
     * @param traceId correlation identifier generated by the publisher
     * @return the wire representation of the job
     */
    public static JobMessage from(JobEntity job, String traceId) {
        Objects.requireNonNull(job, "job must not be null");
        return new JobMessage(
                job.getId(),
                job.getJobType(),
                job.getPayload(),
                job.getRetryCount(),
                traceId
        );
    }
}
